/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DesignRouteImport } from './routes/design'
import { Route as RemoteRouteImport } from './routes/_remote'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CliRouteRouteImport } from './routes/cli/route'
import { Route as RemoteIndexRouteImport } from './routes/_remote/index'
import { Route as DesignFramesRouteImport } from './routes/design_.frames'
import { Route as RemoteRpcWallet_revokeAccessKeyRouteImport } from './routes/_remote/rpc/wallet_revokeAccessKey'
import { Route as RemoteRpcWallet_connectRouteImport } from './routes/_remote/rpc/wallet_connect'
import { Route as RemoteRpcWallet_authorizeAccessKeyRouteImport } from './routes/_remote/rpc/wallet_authorizeAccessKey'
import { Route as RemoteRpcPersonal_signRouteImport } from './routes/_remote/rpc/personal_sign'
import { Route as RemoteRpcEth_signTypedData_v4RouteImport } from './routes/_remote/rpc/eth_signTypedData_v4'
import { Route as RemoteRpcEth_signTransactionRouteImport } from './routes/_remote/rpc/eth_signTransaction'
import { Route as RemoteRpcEth_sendTransactionSyncRouteImport } from './routes/_remote/rpc/eth_sendTransactionSync'
import { Route as RemoteRpcEth_sendTransactionRouteImport } from './routes/_remote/rpc/eth_sendTransaction'

const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/_remote',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRouteRoute = CliRouteRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteIndexRoute = RemoteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RemoteRoute,
} as any)
const DesignFramesRoute = DesignFramesRouteImport.update({
  id: '/design_/frames',
  path: '/design/frames',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRpcWallet_revokeAccessKeyRoute =
  RemoteRpcWallet_revokeAccessKeyRouteImport.update({
    id: '/rpc/wallet_revokeAccessKey',
    path: '/rpc/wallet_revokeAccessKey',
    getParentRoute: () => RemoteRoute,
  } as any)
const RemoteRpcWallet_connectRoute = RemoteRpcWallet_connectRouteImport.update({
  id: '/rpc/wallet_connect',
  path: '/rpc/wallet_connect',
  getParentRoute: () => RemoteRoute,
} as any)
const RemoteRpcWallet_authorizeAccessKeyRoute =
  RemoteRpcWallet_authorizeAccessKeyRouteImport.update({
    id: '/rpc/wallet_authorizeAccessKey',
    path: '/rpc/wallet_authorizeAccessKey',
    getParentRoute: () => RemoteRoute,
  } as any)
const RemoteRpcPersonal_signRoute = RemoteRpcPersonal_signRouteImport.update({
  id: '/rpc/personal_sign',
  path: '/rpc/personal_sign',
  getParentRoute: () => RemoteRoute,
} as any)
const RemoteRpcEth_signTypedData_v4Route =
  RemoteRpcEth_signTypedData_v4RouteImport.update({
    id: '/rpc/eth_signTypedData_v4',
    path: '/rpc/eth_signTypedData_v4',
    getParentRoute: () => RemoteRoute,
  } as any)
const RemoteRpcEth_signTransactionRoute =
  RemoteRpcEth_signTransactionRouteImport.update({
    id: '/rpc/eth_signTransaction',
    path: '/rpc/eth_signTransaction',
    getParentRoute: () => RemoteRoute,
  } as any)
const RemoteRpcEth_sendTransactionSyncRoute =
  RemoteRpcEth_sendTransactionSyncRouteImport.update({
    id: '/rpc/eth_sendTransactionSync',
    path: '/rpc/eth_sendTransactionSync',
    getParentRoute: () => RemoteRoute,
  } as any)
const RemoteRpcEth_sendTransactionRoute =
  RemoteRpcEth_sendTransactionRouteImport.update({
    id: '/rpc/eth_sendTransaction',
    path: '/rpc/eth_sendTransaction',
    getParentRoute: () => RemoteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/cli': typeof CliRouteRoute
  '/$': typeof SplatRoute
  '/': typeof RemoteIndexRoute
  '/design': typeof DesignRoute
  '/email': typeof EmailRoute
  '/design/frames': typeof DesignFramesRoute
  '/rpc/eth_sendTransaction': typeof RemoteRpcEth_sendTransactionRoute
  '/rpc/eth_sendTransactionSync': typeof RemoteRpcEth_sendTransactionSyncRoute
  '/rpc/eth_signTransaction': typeof RemoteRpcEth_signTransactionRoute
  '/rpc/eth_signTypedData_v4': typeof RemoteRpcEth_signTypedData_v4Route
  '/rpc/personal_sign': typeof RemoteRpcPersonal_signRoute
  '/rpc/wallet_authorizeAccessKey': typeof RemoteRpcWallet_authorizeAccessKeyRoute
  '/rpc/wallet_connect': typeof RemoteRpcWallet_connectRoute
  '/rpc/wallet_revokeAccessKey': typeof RemoteRpcWallet_revokeAccessKeyRoute
}
export interface FileRoutesByTo {
  '/cli': typeof CliRouteRoute
  '/$': typeof SplatRoute
  '/design': typeof DesignRoute
  '/email': typeof EmailRoute
  '/design/frames': typeof DesignFramesRoute
  '/': typeof RemoteIndexRoute
  '/rpc/eth_sendTransaction': typeof RemoteRpcEth_sendTransactionRoute
  '/rpc/eth_sendTransactionSync': typeof RemoteRpcEth_sendTransactionSyncRoute
  '/rpc/eth_signTransaction': typeof RemoteRpcEth_signTransactionRoute
  '/rpc/eth_signTypedData_v4': typeof RemoteRpcEth_signTypedData_v4Route
  '/rpc/personal_sign': typeof RemoteRpcPersonal_signRoute
  '/rpc/wallet_authorizeAccessKey': typeof RemoteRpcWallet_authorizeAccessKeyRoute
  '/rpc/wallet_connect': typeof RemoteRpcWallet_connectRoute
  '/rpc/wallet_revokeAccessKey': typeof RemoteRpcWallet_revokeAccessKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/cli': typeof CliRouteRoute
  '/$': typeof SplatRoute
  '/_remote': typeof RemoteRouteWithChildren
  '/design': typeof DesignRoute
  '/email': typeof EmailRoute
  '/design_/frames': typeof DesignFramesRoute
  '/_remote/': typeof RemoteIndexRoute
  '/_remote/rpc/eth_sendTransaction': typeof RemoteRpcEth_sendTransactionRoute
  '/_remote/rpc/eth_sendTransactionSync': typeof RemoteRpcEth_sendTransactionSyncRoute
  '/_remote/rpc/eth_signTransaction': typeof RemoteRpcEth_signTransactionRoute
  '/_remote/rpc/eth_signTypedData_v4': typeof RemoteRpcEth_signTypedData_v4Route
  '/_remote/rpc/personal_sign': typeof RemoteRpcPersonal_signRoute
  '/_remote/rpc/wallet_authorizeAccessKey': typeof RemoteRpcWallet_authorizeAccessKeyRoute
  '/_remote/rpc/wallet_connect': typeof RemoteRpcWallet_connectRoute
  '/_remote/rpc/wallet_revokeAccessKey': typeof RemoteRpcWallet_revokeAccessKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cli'
    | '/$'
    | '/'
    | '/design'
    | '/email'
    | '/design/frames'
    | '/rpc/eth_sendTransaction'
    | '/rpc/eth_sendTransactionSync'
    | '/rpc/eth_signTransaction'
    | '/rpc/eth_signTypedData_v4'
    | '/rpc/personal_sign'
    | '/rpc/wallet_authorizeAccessKey'
    | '/rpc/wallet_connect'
    | '/rpc/wallet_revokeAccessKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cli'
    | '/$'
    | '/design'
    | '/email'
    | '/design/frames'
    | '/'
    | '/rpc/eth_sendTransaction'
    | '/rpc/eth_sendTransactionSync'
    | '/rpc/eth_signTransaction'
    | '/rpc/eth_signTypedData_v4'
    | '/rpc/personal_sign'
    | '/rpc/wallet_authorizeAccessKey'
    | '/rpc/wallet_connect'
    | '/rpc/wallet_revokeAccessKey'
  id:
    | '__root__'
    | '/cli'
    | '/$'
    | '/_remote'
    | '/design'
    | '/email'
    | '/design_/frames'
    | '/_remote/'
    | '/_remote/rpc/eth_sendTransaction'
    | '/_remote/rpc/eth_sendTransactionSync'
    | '/_remote/rpc/eth_signTransaction'
    | '/_remote/rpc/eth_signTypedData_v4'
    | '/_remote/rpc/personal_sign'
    | '/_remote/rpc/wallet_authorizeAccessKey'
    | '/_remote/rpc/wallet_connect'
    | '/_remote/rpc/wallet_revokeAccessKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CliRouteRoute: typeof CliRouteRoute
  SplatRoute: typeof SplatRoute
  RemoteRoute: typeof RemoteRouteWithChildren
  DesignRoute: typeof DesignRoute
  EmailRoute: typeof EmailRoute
  DesignFramesRoute: typeof DesignFramesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_remote': {
      id: '/_remote'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_remote/': {
      id: '/_remote/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RemoteIndexRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/design_/frames': {
      id: '/design_/frames'
      path: '/design/frames'
      fullPath: '/design/frames'
      preLoaderRoute: typeof DesignFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_remote/rpc/wallet_revokeAccessKey': {
      id: '/_remote/rpc/wallet_revokeAccessKey'
      path: '/rpc/wallet_revokeAccessKey'
      fullPath: '/rpc/wallet_revokeAccessKey'
      preLoaderRoute: typeof RemoteRpcWallet_revokeAccessKeyRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/wallet_connect': {
      id: '/_remote/rpc/wallet_connect'
      path: '/rpc/wallet_connect'
      fullPath: '/rpc/wallet_connect'
      preLoaderRoute: typeof RemoteRpcWallet_connectRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/wallet_authorizeAccessKey': {
      id: '/_remote/rpc/wallet_authorizeAccessKey'
      path: '/rpc/wallet_authorizeAccessKey'
      fullPath: '/rpc/wallet_authorizeAccessKey'
      preLoaderRoute: typeof RemoteRpcWallet_authorizeAccessKeyRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/personal_sign': {
      id: '/_remote/rpc/personal_sign'
      path: '/rpc/personal_sign'
      fullPath: '/rpc/personal_sign'
      preLoaderRoute: typeof RemoteRpcPersonal_signRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/eth_signTypedData_v4': {
      id: '/_remote/rpc/eth_signTypedData_v4'
      path: '/rpc/eth_signTypedData_v4'
      fullPath: '/rpc/eth_signTypedData_v4'
      preLoaderRoute: typeof RemoteRpcEth_signTypedData_v4RouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/eth_signTransaction': {
      id: '/_remote/rpc/eth_signTransaction'
      path: '/rpc/eth_signTransaction'
      fullPath: '/rpc/eth_signTransaction'
      preLoaderRoute: typeof RemoteRpcEth_signTransactionRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/eth_sendTransactionSync': {
      id: '/_remote/rpc/eth_sendTransactionSync'
      path: '/rpc/eth_sendTransactionSync'
      fullPath: '/rpc/eth_sendTransactionSync'
      preLoaderRoute: typeof RemoteRpcEth_sendTransactionSyncRouteImport
      parentRoute: typeof RemoteRoute
    }
    '/_remote/rpc/eth_sendTransaction': {
      id: '/_remote/rpc/eth_sendTransaction'
      path: '/rpc/eth_sendTransaction'
      fullPath: '/rpc/eth_sendTransaction'
      preLoaderRoute: typeof RemoteRpcEth_sendTransactionRouteImport
      parentRoute: typeof RemoteRoute
    }
  }
}

interface RemoteRouteChildren {
  RemoteIndexRoute: typeof RemoteIndexRoute
  RemoteRpcEth_sendTransactionRoute: typeof RemoteRpcEth_sendTransactionRoute
  RemoteRpcEth_sendTransactionSyncRoute: typeof RemoteRpcEth_sendTransactionSyncRoute
  RemoteRpcEth_signTransactionRoute: typeof RemoteRpcEth_signTransactionRoute
  RemoteRpcEth_signTypedData_v4Route: typeof RemoteRpcEth_signTypedData_v4Route
  RemoteRpcPersonal_signRoute: typeof RemoteRpcPersonal_signRoute
  RemoteRpcWallet_authorizeAccessKeyRoute: typeof RemoteRpcWallet_authorizeAccessKeyRoute
  RemoteRpcWallet_connectRoute: typeof RemoteRpcWallet_connectRoute
  RemoteRpcWallet_revokeAccessKeyRoute: typeof RemoteRpcWallet_revokeAccessKeyRoute
}

const RemoteRouteChildren: RemoteRouteChildren = {
  RemoteIndexRoute: RemoteIndexRoute,
  RemoteRpcEth_sendTransactionRoute: RemoteRpcEth_sendTransactionRoute,
  RemoteRpcEth_sendTransactionSyncRoute: RemoteRpcEth_sendTransactionSyncRoute,
  RemoteRpcEth_signTransactionRoute: RemoteRpcEth_signTransactionRoute,
  RemoteRpcEth_signTypedData_v4Route: RemoteRpcEth_signTypedData_v4Route,
  RemoteRpcPersonal_signRoute: RemoteRpcPersonal_signRoute,
  RemoteRpcWallet_authorizeAccessKeyRoute:
    RemoteRpcWallet_authorizeAccessKeyRoute,
  RemoteRpcWallet_connectRoute: RemoteRpcWallet_connectRoute,
  RemoteRpcWallet_revokeAccessKeyRoute: RemoteRpcWallet_revokeAccessKeyRoute,
}

const RemoteRouteWithChildren =
  RemoteRoute._addFileChildren(RemoteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CliRouteRoute: CliRouteRoute,
  SplatRoute: SplatRoute,
  RemoteRoute: RemoteRouteWithChildren,
  DesignRoute: DesignRoute,
  EmailRoute: EmailRoute,
  DesignFramesRoute: DesignFramesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
