allowBuilds:
  bufferutil: true
  cloudflared: true
  cpu-features: true
  esbuild: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true
  ssh2: true
  utf-8-validate: true
  workerd: true

blockExoticSubdeps: true

catalog:
  '@cloudflare/vite-plugin': ^1.31.2
  '@cloudflare/workers-types': ^4.20260317.1
  '@tanstack/react-query': ^5.97.0
  '@tanstack/react-router': ^1.168.19
  '@tanstack/react-start': ^1.166.7
  '@total-typescript/ts-reset': ^0.6.1
  '@types/node': ^25.6.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/devtools': ^0.1.15
  '@vitejs/plugin-react': ^5.2.0
  '@wagmi/core': ^3.4.9
  hono: ^4.12.14
  mppx: ^0.6.19
  ox: ~0.14.18
  prool: ~0.2.4
  react: ^19.2.5
  react-dom: ^19.2.5
  tsx: ^4.21.0
  typed-query-selector: ^2.12.1
  typescript: ^5.9.3
  viem: ^2.48.8
  vite: ^8.0.5
  vite-plus: ~0.1.18
  vp: npm:vite-plus@~0.1.18
  wagmi: ^3.6.11
  wrangler: ^4.85.0
  zod: ^4.3.6

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - incur
  - mppx
  - ox
  - regen-ui
  - secretlint
  - viem
  - vite-plus

nodeOptions: '--disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning'

overrides:
  accounts: 'workspace:*'
  ox: '~0.14.18'
  protobufjs: '7.5.5'
  react: 'catalog:'
  react-dom: 'catalog:'
  viem: 'catalog:'
  vite-plus: 'catalog:'
  vp: 'catalog:'
  wrangler: 'catalog:'

packages:
  - .
  - examples/*
  - playgrounds/*
  - ref-impls/*

peerDependencyRules:
  allowedVersions:
    accounts: '*'

shellEmulator: true

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
