import * as React from 'react'

type Pending = {
  account?: string | undefined
  accessKeyAddress: string
  chainId: string
  code: string
  expiry: number
  keyType: string
}

type Approved = {
  accountAddress: string
  status: 'authorized'
}

type PendingState =
  | { status: 'idle' }
  | { status: 'loading' }
  | { pending: Pending; status: 'ready' }
  | { error: string; status: 'error' }

type ApproveState =
  | { status: 'idle' }
  | { approved: Approved; code: string; status: 'approved' }
  | { error: string; status: 'error' }

async function loadPending(code: string): Promise<PendingState> {
  try {
    return {
      pending: await fetch(`/cli-auth/pending/${code}`).then((response) => response.json()),
      status: 'ready',
    }
  } catch (error) {
    return {
      error: error instanceof Error ? error.message : 'Request failed.',
      status: 'error',
    }
  }
}

/** Minimal approval page for the CLI auth reference implementation. */
export function App() {
  const current = new URLSearchParams(window.location.search).get('code')
  const code = current ? current : ''
  const [pending, setPending] = React.useState<PendingState>(
    code ? { status: 'loading' } : { status: 'idle' },
  )
  const [approveState, approve, approving] = React.useActionState(
    async (_: ApproveState, formData: FormData): Promise<ApproveState> => {
      try {
        return {
          approved: await fetch('/cli-auth/approve', {
            body: JSON.stringify({ code: String(formData.get('code') ?? '') }),
            headers: { 'content-type': 'application/json' },
            method: 'POST',
          }).then((response) => response.json()),
          code: String(formData.get('code') ?? ''),
          status: 'approved',
        }
      } catch (error) {
        return {
          error: error instanceof Error ? error.message : 'Request failed.',
          status: 'error',
        }
      }
    },
    { status: 'idle' },
  )

  React.useEffect(() => {
    if (!code) {
      setPending({ status: 'idle' })
      return
    }

    let cancelled = false
    setPending({ status: 'loading' })

    void loadPending(code).then((result) => {
      if (!cancelled) setPending(result)
    })

    return () => {
      cancelled = true
    }
  }, [code])

  return (
    <main>
      <h1>CLI auth</h1>
      <p>Approve the device code generated by your CLI.</p>

      <form action="/" method="get">
        <label htmlFor="code">Device code</label>
        <input defaultValue={code} id="code" name="code" />
        <button type="submit">Load request</button>
      </form>

      {pending.status === 'idle' && <p>Paste a device code to load the pending request.</p>}
      {pending.status === 'loading' && <p>Loading request...</p>}
      {pending.status === 'error' && <p>{pending.error}</p>}
      {approveState.status === 'approved' && (
        <>
          <h2>Approved</h2>
          <p>
            Device code <strong>{approveState.code}</strong> was authorized by{' '}
            <code>{approveState.approved.accountAddress}</code>.
          </p>
          <p>You can return to the CLI.</p>
        </>
      )}
      {approveState.status !== 'approved' && pending.status === 'ready' && (
        <>
          <h2>Pending request</h2>
          <dl>
            <dt>Device code</dt>
            <dd>{pending.pending.code}</dd>
            <dt>Access key</dt>
            <dd>{pending.pending.accessKeyAddress}</dd>
            {pending.pending.account && (
              <>
                <dt>Requested account</dt>
                <dd>{pending.pending.account}</dd>
              </>
            )}
            <dt>Chain ID</dt>
            <dd>{pending.pending.chainId}</dd>
            <dt>Key type</dt>
            <dd>{pending.pending.keyType}</dd>
            <dt>Expires</dt>
            <dd>{new Date(pending.pending.expiry * 1000).toISOString()}</dd>
          </dl>
          {approveState.status === 'error' && <p>{approveState.error}</p>}
          <form action={approve}>
            <input name="code" type="hidden" value={pending.pending.code} />
            <button type="submit">{approving ? 'Approving...' : 'Approve'}</button>
          </form>
        </>
      )}
    </main>
  )
}
